baseURL: "https://tithe.digital/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Tithe"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Tithe"
  description: "Connecting people and nonprofit organizations by the easiest way to support a cause, making funding better for everyone."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Toronto, ON, CA"

  contact:
    - "team@tithe.digital"

  copyright: "© 2023 Tithe"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

  buttons:
    - name: "Waitlist"
      url: "https://docs.google.com/forms/d/e/1FAIpQLScXmjaQBu3bubby5HQCKUwvxsV05em87pvz8sCpDri2ZjzYgA/viewform?usp=sf_link"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "Our team"
    #   url: "/#"
    #   weight: 2

    # - name: "Blog"
    #   url: "/posts"
    #   weight: 3

taxonomies:
  series: "series"
  tags: "tags"
